import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'ar' | 'zh' | 'pt' | 'hi';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  translate: (enText: string) => string;
}

const GLOBAL_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    "⚽ Fan Portal": "⚽ Fan Portal",
    "📊 Executive": "📊 Executive",
    "🚨 Emergency": "🚨 Emergency",
    "⚙️ Operations": "⚙️ Operations",
    "👥 Crowd": "👥 Crowd",
    "🤝 Volunteers": "🤝 Volunteers",
    "🚌 Transport": "🚌 Transport",
    "Verified Live": "Verified Live",
    "AI Stadium Concierge": "AI Stadium Concierge",
    "Live Stadium Services Online": "Live Stadium Services Online",
    "SMART ASSISTANCE READY": "SMART ASSISTANCE READY",
    "Live Score": "Live Score",
    "Attendance": "Attendance",
    "Weather": "Weather",
    "Possession": "Possession",
    "Crowd Flow": "Crowd Flow",
    "Security": "Security",
    "Est. Egress": "Est. Egress",
    "Match telemetry ready for active tournament events.": "Match telemetry ready for active tournament events.",
    "One-Touch Smart Routing": "One-Touch Smart Routing",
    "Copied": "Copied",
    "Send": "Send",
    "Interactive 12-Stage Fan Journey": "Interactive 12-Stage Fan Journey",
    "Map your entire stadium experience with AI-optimized routing": "Map your entire stadium experience with AI-optimized routing",
    "Verified Venue Points of Interest": "Verified Venue Points of Interest",
    "Verified Live Venue Telemetry & Synchronized Operations": "Verified Live Venue Telemetry & Synchronized Operations",
    "Live AI Alert Center": "Live AI Alert Center",
    "Active Stadium Notifications": "Active Stadium Notifications",
    "ALERTS": "ALERTS",
    "Zone:": "Zone:",
    "Status:": "Status:",
    "AI Active": "AI Active",
    "Collapse": "Collapse",
    "Details": "Details",
    "DISMISS": "DISMISS",
    "No active stadium advisories": "No active stadium advisories",
    "Where is Gate 4?": "Where is Gate 4?",
    "Where is the nearest restroom?": "Where is the nearest restroom?",
    "What is the parking situation?": "What is the parking situation?",
    "What is the current score?": "What is the current score?",
    "vs": "vs",
    "Arrival": "Arrival",
    "Pre-Match": "Pre-Match",
    "Match": "Match",
    "Departure": "Departure",
    "ALL": "ALL",
    "FOOD": "FOOD",
    "RESTROOM": "RESTROOM",
    "MERCH": "MERCH",
    "SECURITY": "SECURITY",
    "Ask the AI Stadium Concierge": "Ask the AI Stadium Concierge...",
    "Tournament Live": "Tournament Live"
  ,
    "Est. Time": "Est. Time",
    "min": "min",
    "Confidence": "Confidence",
    "Crowd Density": "Crowd Density",
    "Low": "Low",
    "Accessibility": "Accessibility",
    "ADA Certified": "ADA Certified",
    "Verified Live • Grounded Stadium Knowledge": "Verified Live • Grounded Stadium Knowledge",
    "Voice Output Audio": "Voice Output Audio",
    "Copy response": "Copy response",
    "Helpful response": "Helpful response",
    "Needs improvement": "Needs improvement",
    "Help me": "Help me",
    "Regenerate response": "Regenerate response",
    "Toggle speech input": "Toggle speech input",
    "Speech input": "Speech input",
    "Select any stage to view live synchronized recommendations and venue SLAs": "Select any stage to view live synchronized recommendations and venue SLAs",
    "Ready": "Ready",
    "ACTIVE STAGE TELEMETRY": "ACTIVE STAGE TELEMETRY",
    "GUIDANCE": "GUIDANCE",
    "Predictive AI wayfinding and synchronized venue recommendations.": "Predictive AI wayfinding and synchronized venue recommendations.",
    "SLA ACTIVE": "SLA ACTIVE"
  },
  es: {
    "⚽ Fan Portal": "⚽ Portal de Aficionados",
    "📊 Executive": "📊 Ejecutivo",
    "🚨 Emergency": "🚨 Emergencia",
    "⚙️ Operations": "⚙️ Operaciones",
    "👥 Crowd": "👥 Multitud",
    "🤝 Volunteers": "🤝 Voluntarios",
    "🚌 Transport": "🚌 Transporte",
    "Verified Live": "Verificado en Vivo",
    "AI Stadium Concierge": "Conserje IA del Estadio",
    "Live Stadium Services Online": "Servicios en Vivo Conectados",
    "SMART ASSISTANCE READY": "ASISTENCIA INTELIGENTE LISTA",
    "Live Score": "Marcador en Vivo",
    "Attendance": "Asistencia",
    "Weather": "Clima",
    "Possession": "Posesión",
    "Crowd Flow": "Flujo de Público",
    "Security": "Seguridad",
    "Est. Egress": "Salida Est.",
    "Match telemetry ready for active tournament events.": "Telemetría del partido lista para eventos activos.",
    "One-Touch Smart Routing": "Rutas Inteligentes",
    "Copied": "Copiado",
    "Send": "Enviar",
    "Interactive 12-Stage Fan Journey": "Viaje del Aficionado de 12 Etapas",
    "Map your entire stadium experience with AI-optimized routing": "Mapea tu experiencia con rutas optimizadas por IA",
    "Verified Venue Points of Interest": "Puntos de Interés Verificados",
    "Verified Live Venue Telemetry & Synchronized Operations": "Telemetría en Vivo y Operaciones Sincronizadas",
    "Live AI Alert Center": "Centro de Alertas de IA en Vivo",
    "Active Stadium Notifications": "Notificaciones Activas del Estadio",
    "ALERTS": "ALERTAS",
    "Zone:": "Zona:",
    "Status:": "Estado:",
    "AI Active": "IA Activa",
    "Collapse": "Ocultar",
    "Details": "Detalles",
    "DISMISS": "DESCARTAR",
    "No active stadium advisories": "No hay avisos activos",
    "Where is Gate 4?": "¿Dónde está la Puerta 4?",
    "Where is the nearest restroom?": "¿Dónde está el baño más cercano?",
    "What is the parking situation?": "¿Cuál es la situación del estacionamiento?",
    "What is the current score?": "¿Cuál es el marcador actual?",
    "vs": "vs",
    "Arrival": "Llegada",
    "Pre-Match": "Pre-Partido",
    "Match": "Partido",
    "Departure": "Salida",
    "ALL": "TODO",
    "FOOD": "COMIDA",
    "RESTROOM": "BAÑOS",
    "MERCH": "TIENDA",
    "SECURITY": "SEGURIDAD",
    "Ask the AI Stadium Concierge": "Pregúntale al Conserje IA...",
    "Tournament Live": "Torneo en Vivo"
  ,
    "Est. Time": "Est. Time",
    "min": "min",
    "Confidence": "Confidence",
    "Crowd Density": "Crowd Density",
    "Low": "Low",
    "Accessibility": "Accessibility",
    "ADA Certified": "ADA Certified",
    "Verified Live • Grounded Stadium Knowledge": "Verified Live • Grounded Stadium Knowledge",
    "Voice Output Audio": "Voice Output Audio",
    "Copy response": "Copy response",
    "Helpful response": "Helpful response",
    "Needs improvement": "Needs improvement",
    "Help me": "Help me",
    "Regenerate response": "Regenerate response",
    "Toggle speech input": "Toggle speech input",
    "Speech input": "Speech input",
    "Select any stage to view live synchronized recommendations and venue SLAs": "Select any stage to view live synchronized recommendations and venue SLAs",
    "Ready": "Ready",
    "ACTIVE STAGE TELEMETRY": "ACTIVE STAGE TELEMETRY",
    "GUIDANCE": "GUIDANCE",
    "Predictive AI wayfinding and synchronized venue recommendations.": "Predictive AI wayfinding and synchronized venue recommendations.",
    "SLA ACTIVE": "SLA ACTIVE"
  },
  fr: {
    "⚽ Fan Portal": "⚽ Portail des Fans",
    "📊 Executive": "📊 Exécutif",
    "🚨 Emergency": "🚨 Urgences",
    "⚙️ Operations": "⚙️ Opérations",
    "👥 Crowd": "👥 Foule",
    "🤝 Volunteers": "🤝 Bénévoles",
    "🚌 Transport": "🚌 Transports",
    "Verified Live": "Vérifié en Direct",
    "AI Stadium Concierge": "Concierge IA du Stade",
    "Live Stadium Services Online": "Services en Direct Connectés",
    "SMART ASSISTANCE READY": "ASSISTANCE INTELLIGENTE PRÊTE",
    "Live Score": "Score en Direct",
    "Attendance": "Affluence",
    "Weather": "Météo",
    "Possession": "Possession",
    "Crowd Flow": "Flux de Foule",
    "Security": "Sécurité",
    "Est. Egress": "Sortie Est.",
    "Match telemetry ready for active tournament events.": "Télémétrie du match prête pour les événements actifs.",
    "One-Touch Smart Routing": "Itinéraires Intelligents",
    "Copied": "Copié",
    "Send": "Envoyer",
    "Interactive 12-Stage Fan Journey": "Parcours Interactif des Fans en 12 Étapes",
    "Map your entire stadium experience with AI-optimized routing": "Cartographiez votre expérience avec des itinéraires optimisés par l'IA",
    "Verified Venue Points of Interest": "Points d'Intérêt Vérifiés",
    "Verified Live Venue Telemetry & Synchronized Operations": "Télémétrie en Direct et Opérations Synchronisées",
    "Live AI Alert Center": "Centre d'Alertes IA en Direct",
    "Active Stadium Notifications": "Notifications Actives du Stade",
    "ALERTS": "ALERTES",
    "Zone:": "Zone:",
    "Status:": "Statut:",
    "AI Active": "IA Active",
    "Collapse": "Masquer",
    "Details": "Détails",
    "DISMISS": "IGNORER",
    "No active stadium advisories": "Aucun avis actif",
    "Where is Gate 4?": "Où est la Porte 4 ?",
    "Where is the nearest restroom?": "Où sont les toilettes les plus proches ?",
    "What is the parking situation?": "Quelle est la situation du parking ?",
    "What is the current score?": "Quel est le score actuel ?",
    "vs": "contre",
    "Arrival": "Arrivée",
    "Pre-Match": "Avant-Match",
    "Match": "Match",
    "Departure": "Départ",
    "ALL": "TOUT",
    "FOOD": "NOURRITURE",
    "RESTROOM": "TOILETTES",
    "MERCH": "BOUTIQUE",
    "SECURITY": "SÉCURITÉ",
    "Ask the AI Stadium Concierge": "Demandez au Concierge IA...",
    "Tournament Live": "Tournoi en Direct"
  ,
    "Est. Time": "Est. Time",
    "min": "min",
    "Confidence": "Confidence",
    "Crowd Density": "Crowd Density",
    "Low": "Low",
    "Accessibility": "Accessibility",
    "ADA Certified": "ADA Certified",
    "Verified Live • Grounded Stadium Knowledge": "Verified Live • Grounded Stadium Knowledge",
    "Voice Output Audio": "Voice Output Audio",
    "Copy response": "Copy response",
    "Helpful response": "Helpful response",
    "Needs improvement": "Needs improvement",
    "Help me": "Help me",
    "Regenerate response": "Regenerate response",
    "Toggle speech input": "Toggle speech input",
    "Speech input": "Speech input",
    "Select any stage to view live synchronized recommendations and venue SLAs": "Select any stage to view live synchronized recommendations and venue SLAs",
    "Ready": "Ready",
    "ACTIVE STAGE TELEMETRY": "ACTIVE STAGE TELEMETRY",
    "GUIDANCE": "GUIDANCE",
    "Predictive AI wayfinding and synchronized venue recommendations.": "Predictive AI wayfinding and synchronized venue recommendations.",
    "SLA ACTIVE": "SLA ACTIVE"
  },
  de: {
    "⚽ Fan Portal": "⚽ Fan-Portal",
    "📊 Executive": "📊 Exekutive",
    "🚨 Emergency": "🚨 Notruf",
    "⚙️ Operations": "⚙️ Betrieb",
    "👥 Crowd": "👥 Menge",
    "🤝 Volunteers": "🤝 Freiwillige",
    "🚌 Transport": "🚌 Verkehr",
    "Verified Live": "Live Verifiziert",
    "AI Stadium Concierge": "KI-Stadionassistent",
    "Live Stadium Services Online": "Stadiondienste Online",
    "SMART ASSISTANCE READY": "INTELLIGENTE ASSISTENZ BEREIT",
    "Live Score": "Live-Spielstand",
    "Attendance": "Zuschauer",
    "Weather": "Wetter",
    "Possession": "Ballbesitz",
    "Crowd Flow": "Menschenfluss",
    "Security": "Sicherheit",
    "Est. Egress": "Gesch. Abfluss",
    "Match telemetry ready for active tournament events.": "Spieltelemetrie bereit für aktive Turniere.",
    "One-Touch Smart Routing": "Intelligentes Routing",
    "Copied": "Kopiert",
    "Send": "Senden",
    "Interactive 12-Stage Fan Journey": "Interaktive 12-Stufen Fan-Reise",
    "Map your entire stadium experience with AI-optimized routing": "Planen Sie Ihr Erlebnis mit KI-optimiertem Routing",
    "Verified Venue Points of Interest": "Verifizierte Sonderziele",
    "Verified Live Venue Telemetry & Synchronized Operations": "Verifizierte Live-Telemetrie & Synchronisierte Vorgänge",
    "Live AI Alert Center": "Live KI-Alarmzentrum",
    "Active Stadium Notifications": "Aktive Stadionbenachrichtigungen",
    "ALERTS": "ALARME",
    "Zone:": "Zone:",
    "Status:": "Status:",
    "AI Active": "KI Aktiv",
    "Collapse": "Einklappen",
    "Details": "Details",
    "DISMISS": "SCHLIEßEN",
    "No active stadium advisories": "Keine aktiven Stadionhinweise",
    "Where is Gate 4?": "Wo ist Tor 4?",
    "Where is the nearest restroom?": "Wo ist die nächste Toilette?",
    "What is the parking situation?": "Wie ist die Parkplatzsituation?",
    "What is the current score?": "Wie ist der aktuelle Spielstand?",
    "vs": "gegen",
    "Arrival": "Ankunft",
    "Pre-Match": "Vor dem Spiel",
    "Match": "Spiel",
    "Departure": "Abreise",
    "ALL": "ALLE",
    "FOOD": "ESSEN",
    "RESTROOM": "TOILETTEN",
    "MERCH": "SHOP",
    "SECURITY": "SICHERHEIT",
    "Ask the AI Stadium Concierge": "Fragen Sie den KI-Assistenten...",
    "Tournament Live": "Turnier Live"
  ,
    "Est. Time": "Est. Time",
    "min": "min",
    "Confidence": "Confidence",
    "Crowd Density": "Crowd Density",
    "Low": "Low",
    "Accessibility": "Accessibility",
    "ADA Certified": "ADA Certified",
    "Verified Live • Grounded Stadium Knowledge": "Verified Live • Grounded Stadium Knowledge",
    "Voice Output Audio": "Voice Output Audio",
    "Copy response": "Copy response",
    "Helpful response": "Helpful response",
    "Needs improvement": "Needs improvement",
    "Help me": "Help me",
    "Regenerate response": "Regenerate response",
    "Toggle speech input": "Toggle speech input",
    "Speech input": "Speech input",
    "Select any stage to view live synchronized recommendations and venue SLAs": "Select any stage to view live synchronized recommendations and venue SLAs",
    "Ready": "Ready",
    "ACTIVE STAGE TELEMETRY": "ACTIVE STAGE TELEMETRY",
    "GUIDANCE": "GUIDANCE",
    "Predictive AI wayfinding and synchronized venue recommendations.": "Predictive AI wayfinding and synchronized venue recommendations.",
    "SLA ACTIVE": "SLA ACTIVE"
  },
  ar: {
    "⚽ Fan Portal": "⚽ بوابة المشجعين",
    "📊 Executive": "📊 الإدارة العليا",
    "🚨 Emergency": "🚨 الطوارئ",
    "⚙️ Operations": "⚙️ العمليات",
    "👥 Crowd": "👥 الحشود",
    "🤝 Volunteers": "🤝 المتطوعين",
    "🚌 Transport": "🚌 المواصلات",
    "Verified Live": "تم التحقق مباشرة",
    "AI Stadium Concierge": "المساعد الذكي للملعب",
    "Live Stadium Services Online": "خدمات الملعب المباشرة متصلة",
    "SMART ASSISTANCE READY": "المساعدة الذكية جاهزة",
    "Live Score": "النتيجة المباشرة",
    "Attendance": "الحضور",
    "Weather": "الطقس",
    "Possession": "الاستحواذ",
    "Crowd Flow": "تدفق الحشود",
    "Security": "الأمن",
    "Est. Egress": "وقت الخروج",
    "Match telemetry ready for active tournament events.": "بيانات المباراة جاهزة للأحداث النشطة.",
    "One-Touch Smart Routing": "توجيه ذكي بنقرة واحدة",
    "Copied": "تم النسخ",
    "Send": "إرسال",
    "Interactive 12-Stage Fan Journey": "رحلة المشجع التفاعلية ذات 12 مرحلة",
    "Map your entire stadium experience with AI-optimized routing": "ارسم تجربتك بالكامل مع التوجيه المحسن بالذكاء الاصطناعي",
    "Verified Venue Points of Interest": "النقاط المهمة المعتمدة في الملعب",
    "Verified Live Venue Telemetry & Synchronized Operations": "قياسات الملعب المباشرة والعمليات المتزامنة",
    "Live AI Alert Center": "مركز تنبيهات الذكاء الاصطناعي",
    "Active Stadium Notifications": "إشعارات الملعب النشطة",
    "ALERTS": "التنبيهات",
    "Zone:": "المنطقة:",
    "Status:": "الحالة:",
    "AI Active": "الذكاء الاصطناعي نشط",
    "Collapse": "طي",
    "Details": "التفاصيل",
    "DISMISS": "تجاهل",
    "No active stadium advisories": "لا توجد تنبيهات نشطة للملعب",
    "Where is Gate 4?": "أين تقع البوابة 4؟",
    "Where is the nearest restroom?": "أين أقرب دورة مياه؟",
    "What is the parking situation?": "ما هو وضع مواقف السيارات؟",
    "What is the current score?": "ما هي النتيجة الحالية؟",
    "vs": "ضد",
    "Arrival": "الوصول",
    "Pre-Match": "قبل المباراة",
    "Match": "المباراة",
    "Departure": "المغادرة",
    "ALL": "الكل",
    "FOOD": "الطعام",
    "RESTROOM": "دورات المياه",
    "MERCH": "المتجر",
    "SECURITY": "الأمن",
    "Ask the AI Stadium Concierge": "اسأل المساعد الذكي...",
    "Tournament Live": "البطولة مباشرة"
  ,
    "Est. Time": "Est. Time",
    "min": "min",
    "Confidence": "Confidence",
    "Crowd Density": "Crowd Density",
    "Low": "Low",
    "Accessibility": "Accessibility",
    "ADA Certified": "ADA Certified",
    "Verified Live • Grounded Stadium Knowledge": "Verified Live • Grounded Stadium Knowledge",
    "Voice Output Audio": "Voice Output Audio",
    "Copy response": "Copy response",
    "Helpful response": "Helpful response",
    "Needs improvement": "Needs improvement",
    "Help me": "Help me",
    "Regenerate response": "Regenerate response",
    "Toggle speech input": "Toggle speech input",
    "Speech input": "Speech input",
    "Select any stage to view live synchronized recommendations and venue SLAs": "Select any stage to view live synchronized recommendations and venue SLAs",
    "Ready": "Ready",
    "ACTIVE STAGE TELEMETRY": "ACTIVE STAGE TELEMETRY",
    "GUIDANCE": "GUIDANCE",
    "Predictive AI wayfinding and synchronized venue recommendations.": "Predictive AI wayfinding and synchronized venue recommendations.",
    "SLA ACTIVE": "SLA ACTIVE"
  },
  zh: {
    "⚽ Fan Portal": "⚽ 球迷门户",
    "📊 Executive": "📊 管理仪表板",
    "🚨 Emergency": "🚨 紧急救援",
    "⚙️ Operations": "⚙️ 运营调度",
    "👥 Crowd": "👥 人流情报",
    "🤝 Volunteers": "🤝 志愿者/无障碍",
    "🚌 Transport": "🚌 交通与减碳",
    "Verified Live": "实时已验证",
    "AI Stadium Concierge": "AI 球场管家",
    "Live Stadium Services Online": "实时球场服务在线",
    "SMART ASSISTANCE READY": "智能辅助已就绪",
    "Live Score": "实时比分",
    "Attendance": "上座人数",
    "Weather": "天气",
    "Possession": "控球率",
    "Crowd Flow": "人流状态",
    "Security": "安保级别",
    "Est. Egress": "预计散场",
    "Match telemetry ready for active tournament events.": "比赛遥测已准备就绪。",
    "One-Touch Smart Routing": "一键智能导航",
    "Copied": "已复制",
    "Send": "发送",
    "Interactive 12-Stage Fan Journey": "交互式 12 阶段球迷旅程",
    "Map your entire stadium experience with AI-optimized routing": "使用 AI 优化的路线规划您的整个球场体验",
    "Verified Venue Points of Interest": "已验证场馆兴趣点",
    "Verified Live Venue Telemetry & Synchronized Operations": "实时场馆遥测与同步运营",
    "Live AI Alert Center": "实时 AI 警报中心",
    "Active Stadium Notifications": "活跃场馆通知",
    "ALERTS": "警报",
    "Zone:": "区域:",
    "Status:": "状态:",
    "AI Active": "AI 活跃",
    "Collapse": "折叠",
    "Details": "详情",
    "DISMISS": "忽略",
    "No active stadium advisories": "暂无活跃场馆公告",
    "Where is Gate 4?": "4号门在哪里？",
    "Where is the nearest restroom?": "最近的洗手间在哪里？",
    "What is the parking situation?": "现在的停车情况如何？",
    "What is the current score?": "当前比分是多少？",
    "vs": "对",
    "Arrival": "抵达",
    "Pre-Match": "赛前",
    "Match": "比赛中",
    "Departure": "离场",
    "ALL": "全部",
    "FOOD": "餐饮",
    "RESTROOM": "洗手间",
    "MERCH": "商店",
    "SECURITY": "安保",
    "Ask the AI Stadium Concierge": "向 AI 球场管家提问...",
    "Tournament Live": "赛事直播"
  ,
    "Est. Time": "Est. Time",
    "min": "min",
    "Confidence": "Confidence",
    "Crowd Density": "Crowd Density",
    "Low": "Low",
    "Accessibility": "Accessibility",
    "ADA Certified": "ADA Certified",
    "Verified Live • Grounded Stadium Knowledge": "Verified Live • Grounded Stadium Knowledge",
    "Voice Output Audio": "Voice Output Audio",
    "Copy response": "Copy response",
    "Helpful response": "Helpful response",
    "Needs improvement": "Needs improvement",
    "Help me": "Help me",
    "Regenerate response": "Regenerate response",
    "Toggle speech input": "Toggle speech input",
    "Speech input": "Speech input",
    "Select any stage to view live synchronized recommendations and venue SLAs": "Select any stage to view live synchronized recommendations and venue SLAs",
    "Ready": "Ready",
    "ACTIVE STAGE TELEMETRY": "ACTIVE STAGE TELEMETRY",
    "GUIDANCE": "GUIDANCE",
    "Predictive AI wayfinding and synchronized venue recommendations.": "Predictive AI wayfinding and synchronized venue recommendations.",
    "SLA ACTIVE": "SLA ACTIVE"
  },
  pt: {
    "⚽ Fan Portal": "⚽ Portal do Fã",
    "📊 Executive": "📊 Executivo",
    "🚨 Emergency": "🚨 Emergência",
    "⚙️ Operations": "⚙️ Operações",
    "👥 Crowd": "👥 Multidão",
    "🤝 Volunteers": "🤝 Voluntários",
    "🚌 Transport": "🚌 Transporte",
    "Verified Live": "Verificado ao Vivo",
    "AI Stadium Concierge": "Concierge IA do Estádio",
    "Live Stadium Services Online": "Serviços do Estádio Online",
    "SMART ASSISTANCE READY": "ASSISTÊNCIA INTELIGENTE PRONTA",
    "Live Score": "Placar ao Vivo",
    "Attendance": "Público",
    "Weather": "Clima",
    "Possession": "Posse de Bola",
    "Crowd Flow": "Fluxo de Multidão",
    "Security": "Segurança",
    "Est. Egress": "Saída Est.",
    "Match telemetry ready for active tournament events.": "Telemetria da partida pronta para eventos ativos.",
    "One-Touch Smart Routing": "Rotas Inteligentes",
    "Copied": "Copiado",
    "Send": "Enviar",
    "Interactive 12-Stage Fan Journey": "Jornada Interativa do Fã em 12 Estágios",
    "Map your entire stadium experience with AI-optimized routing": "Mapeie sua experiência com rotas otimizadas por IA",
    "Verified Venue Points of Interest": "Pontos de Interesse Verificados",
    "Verified Live Venue Telemetry & Synchronized Operations": "Telemetria ao Vivo e Operações Sincronizadas",
    "Live AI Alert Center": "Centro de Alertas de IA ao Vivo",
    "Active Stadium Notifications": "Notificações Ativas do Estádio",
    "ALERTS": "ALERTAS",
    "Zone:": "Zona:",
    "Status:": "Status:",
    "AI Active": "IA Ativa",
    "Collapse": "Ocultar",
    "Details": "Detalhes",
    "DISMISS": "DESCARTAR",
    "No active stadium advisories": "Nenhum aviso ativo",
    "Where is Gate 4?": "Onde fica o Portão 4?",
    "Where is the nearest restroom?": "Onde fica o banheiro mais próximo?",
    "What is the parking situation?": "Qual é a situação do estacionamento?",
    "What is the current score?": "Qual é o placar atual?",
    "vs": "vs",
    "Arrival": "Chegada",
    "Pre-Match": "Pré-Jogo",
    "Match": "Jogo",
    "Departure": "Saída",
    "ALL": "TUDO",
    "FOOD": "COMIDA",
    "RESTROOM": "BANHEIROS",
    "MERCH": "LOJA",
    "SECURITY": "SEGURANÇA",
    "Ask the AI Stadium Concierge": "Pergunte ao Concierge IA...",
    "Tournament Live": "Torneio ao Vivo"
  ,
    "Est. Time": "Est. Time",
    "min": "min",
    "Confidence": "Confidence",
    "Crowd Density": "Crowd Density",
    "Low": "Low",
    "Accessibility": "Accessibility",
    "ADA Certified": "ADA Certified",
    "Verified Live • Grounded Stadium Knowledge": "Verified Live • Grounded Stadium Knowledge",
    "Voice Output Audio": "Voice Output Audio",
    "Copy response": "Copy response",
    "Helpful response": "Helpful response",
    "Needs improvement": "Needs improvement",
    "Help me": "Help me",
    "Regenerate response": "Regenerate response",
    "Toggle speech input": "Toggle speech input",
    "Speech input": "Speech input",
    "Select any stage to view live synchronized recommendations and venue SLAs": "Select any stage to view live synchronized recommendations and venue SLAs",
    "Ready": "Ready",
    "ACTIVE STAGE TELEMETRY": "ACTIVE STAGE TELEMETRY",
    "GUIDANCE": "GUIDANCE",
    "Predictive AI wayfinding and synchronized venue recommendations.": "Predictive AI wayfinding and synchronized venue recommendations.",
    "SLA ACTIVE": "SLA ACTIVE"
  },
  hi: {
    "⚽ Fan Portal": "⚽ प्रशंसक पोर्टल",
    "📊 Executive": "📊 कार्यकारी डैशबोर्ड",
    "🚨 Emergency": "🚨 आपातकालीन सेवा",
    "⚙️ Operations": "⚙️ संचालन नियंत्रण",
    "👥 Crowd": "👥 भीड़ प्रबंधन",
    "🤝 Volunteers": "🤝 स्वयंसेवक सहायता",
    "🚌 Transport": "🚌 परिवहन सेवा",
    "Verified Live": "लाइव सत्यापित",
    "AI Stadium Concierge": "स्टेडियम एआई सहायक",
    "Live Stadium Services Online": "लाइव स्टेडियम सेवाएं सक्रिय",
    "SMART ASSISTANCE READY": "स्मार्ट सहायता तैयार",
    "Live Score": "लाइव स्कोर",
    "Attendance": "उपस्थिति",
    "Weather": "मौसम",
    "Possession": "गेंद पर कब्ज़ा",
    "Crowd Flow": "भीड़ का प्रवाह",
    "Security": "सुरक्षा",
    "Est. Egress": "अनुमानित निकास",
    "Match telemetry ready for active tournament events.": "मैच टेलीमेट्री सक्रिय इवेंट्स के लिए तैयार है।",
    "One-Touch Smart Routing": "स्मार्ट रूटिंग",
    "Copied": "कॉपी किया गया",
    "Send": "भेजें",
    "Interactive 12-Stage Fan Journey": "इंटरैक्टिव 12-चरण प्रशंसक यात्रा",
    "Map your entire stadium experience with AI-optimized routing": "एआई-अनुकूलित रूटिंग के साथ अपने स्टेडियम अनुभव की योजना बनाएं",
    "Verified Venue Points of Interest": "सत्यापित स्टेडियम स्थान",
    "Verified Live Venue Telemetry & Synchronized Operations": "लाइव स्टेडियम टेलीमेट्री और सिंक्रनाइज़ ऑपरेशन",
    "Live AI Alert Center": "लाइव एआई अलर्ट सेंटर",
    "Active Stadium Notifications": "सक्रिय स्टेडियम सूचनाएं",
    "ALERTS": "अलर्ट",
    "Zone:": "ज़ोन:",
    "Status:": "स्थिति:",
    "AI Active": "एआई सक्रिय",
    "Collapse": "छिपाएं",
    "Details": "विवरण",
    "DISMISS": "खारिज करें",
    "No active stadium advisories": "कोई सक्रिय स्टेडियम चेतावनी नहीं",
    "Where is Gate 4?": "गेट 4 कहाँ है?",
    "Where is the nearest restroom?": "निकटतम शौचालय कहाँ है?",
    "What is the parking situation?": "पार्किंग की स्थिति क्या है?",
    "What is the current score?": "वर्तमान स्कोर क्या है?",
    "vs": "बनाम",
    "Arrival": "आगमन",
    "Pre-Match": "मैच से पहले",
    "Match": "मैच",
    "Departure": "प्रस्थान",
    "ALL": "सभी",
    "FOOD": "भोजन",
    "RESTROOM": "शौचालय",
    "MERCH": "दुकान",
    "SECURITY": "सुरक्षा",
    "Ask the AI Stadium Concierge": "एआई स्टेडियम सहायक से पूछें...",
    "Tournament Live": "टूर्नामेंट लाइव"
  ,
    "Est. Time": "Est. Time",
    "min": "min",
    "Confidence": "Confidence",
    "Crowd Density": "Crowd Density",
    "Low": "Low",
    "Accessibility": "Accessibility",
    "ADA Certified": "ADA Certified",
    "Verified Live • Grounded Stadium Knowledge": "Verified Live • Grounded Stadium Knowledge",
    "Voice Output Audio": "Voice Output Audio",
    "Copy response": "Copy response",
    "Helpful response": "Helpful response",
    "Needs improvement": "Needs improvement",
    "Help me": "Help me",
    "Regenerate response": "Regenerate response",
    "Toggle speech input": "Toggle speech input",
    "Speech input": "Speech input",
    "Select any stage to view live synchronized recommendations and venue SLAs": "Select any stage to view live synchronized recommendations and venue SLAs",
    "Ready": "Ready",
    "ACTIVE STAGE TELEMETRY": "ACTIVE STAGE TELEMETRY",
    "GUIDANCE": "GUIDANCE",
    "Predictive AI wayfinding and synchronized venue recommendations.": "Predictive AI wayfinding and synchronized venue recommendations.",
    "SLA ACTIVE": "SLA ACTIVE"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('stadiummind_global_lang');
    return (saved as LanguageCode) || 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('stadiummind_global_lang', lang);
  };

  const translate = (enText: string): string => {
    const dict = GLOBAL_TRANSLATIONS[language];
    return dict?.[enText] || enText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

